@startuml
'https://plantuml.com/sequence-diagram

autonumber
User -> ": ActiveEdge": Run()
activate ": ActiveEdge"
": ActiveEdge" -> ":CommandUi": PrintWelcomeMessage()
activate ":CommandUi"
":CommandUi"--> ": ActiveEdge": Welcome message printed
deactivate ":CommandUi"
": ActiveEdge"-> ":Parser": Create Parser object
activate ":Parser"
":Parser" --> ": ActiveEdge": Parser object created
deactivate ":Parser"
": ActiveEdge" -> ":Storage": FetchData()
activate ":Storage"
":Storage" --> ": ActiveEdge": Data fetched from storage
deactivate ":Storage"
": ActiveEdge" -> ":Scanner": NextLine()
activate ":Scanner"
":Scanner" --> ": ActiveEdge": Input received
deactivate ":Scanner"

loop until "bye" is entered
    ": ActiveEdge" -> ":Parser": HandleInput(input)
    activate ":Parser"
    ":Parser" --> ": ActiveEdge": Input handled
    deactivate ":Parser"
    ": ActiveEdge" -> ":Scanner": NextLine()
    activate ":Scanner"
    ":Scanner"--> ": ActiveEdge": Next input received
    deactivate ":Scanner"
end loop

": ActiveEdge"-> ":ByeUi" : PrintByeMessage()
activate ":ByeUi"
":ByeUi" -->": ActiveEdge": Bye message printed
deactivate ":ByeUi"

@enduml